// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd38HA_69zcmRp9ipHQWYEYPYnz7JG_wQ',
    appId: '1:212128572802:web:f3da2c3394acbc473a1b9b',
    messagingSenderId: '212128572802',
    projectId: 'fir-with-teacher',
    authDomain: 'fir-with-teacher.firebaseapp.com',
    storageBucket: 'fir-with-teacher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvxi3Y5ZsSaeCpE85MTsPxwSeiGOLt3Yw',
    appId: '1:212128572802:android:ca285b214631fabb3a1b9b',
    messagingSenderId: '212128572802',
    projectId: 'fir-with-teacher',
    storageBucket: 'fir-with-teacher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW9UlV96f9LFhutIR3x6Wxwytx8BrSxz8',
    appId: '1:212128572802:ios:916d5307629e16463a1b9b',
    messagingSenderId: '212128572802',
    projectId: 'fir-with-teacher',
    storageBucket: 'fir-with-teacher.appspot.com',
    iosBundleId: 'com.example.firebasewithteacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW9UlV96f9LFhutIR3x6Wxwytx8BrSxz8',
    appId: '1:212128572802:ios:605061da27f3fe2f3a1b9b',
    messagingSenderId: '212128572802',
    projectId: 'fir-with-teacher',
    storageBucket: 'fir-with-teacher.appspot.com',
    iosBundleId: 'com.example.firebasewithteacher.RunnerTests',
  );
}
